export class CONSTANTS {
  static readonly AUTH_PROFILE = 'AUTH.PROFILE';
  static readonly AUTH_LOGOUT = 'AUTH.LOGOUT';
  static readonly AUTH_LOGIN = 'AUTH.LOGIN';
  static readonly AUTH_REGISTER = 'AUTH.REGISTER';
  static readonly AUTH_EMAIL = 'AUTH.EMAIL';
  static readonly AUTH_PASSWORD = 'AUTH.PASSWORD';
  static readonly AUTH_CONFIRM_PASSWORD = 'AUTH.CONFIRM_PASSWORD';
  static readonly AUTH_LOGIN_IN_PROFILE = 'AUTH.LOGIN_IN_PROFILE';
  static readonly AUTH_ALREADY_REGISTERED = 'AUTH.ALREADY_REGISTERED';
  static readonly AUTH_PASSWORDS_NOT_MATCH = 'AUTH.PASSWORDS_NOT_MATCH';
  static readonly AUTH_REGISTER_FAILED = 'AUTH.REGISTER_FAILED';
  static readonly AUTH_LOGIN_FAILED = 'AUTH.LOGIN_FAILED';
  static readonly AUTH_NO_ACCOUNT = 'AUTH.NO_ACCOUNT';
  static readonly AUTH_REGISTER_NOW = 'AUTH.REGISTER_NOW';
  static readonly AUTH_GOOGLE_LOGIN = 'AUTH.GOOGLE_LOGIN';
  static readonly AUTH_SETTINGS: 'AUTH_SETTINGS';
  static readonly AUTH_ACCOUNT_SETTINGS = 'AUTH.ACCOUNT_SETTINGS';
  static readonly AUTH_SUBSCRIPTION_SETTINGS = 'AUTH.SUBSCRIPTION_SETTINGS';
  static readonly AUTH_PRIVACY_SETTINGS = 'AUTH.PRIVACY_SETTINGS';
  static readonly AUTH_LOGIN_ERROR = 'AUTH.LOGIN_ERROR';

  static readonly ROUTES = {
    HOME: '',
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    TREE: '/tree',
    MEMBER: '/member',
    AUTH_GOOGLE_LOGIN: '/auth/google',
    SETTINGS: {
      ACCOUNT: '/settings/account',
      SUBSCRIPTION: '/settings/subscription',
      PRIVACY: '/settings/privacy',
    },
    ONBOARDING: {
      OWNER: '/onboarding/owner',
      MOTHER: '/onboarding/mother',
      MATERNAL_GRANDPARENTS: '/onboarding/maternal-grandparents',
      FATHER: '/onboarding/father',
      PATERNAL_GRANDPARENTS: '/onboarding/paternal-grandparents',
    },
  };

  static readonly INFO_OWNER = 'INFO.OWNER';
  static readonly INFO_MOTHER = 'INFO.MOTHER';
  static readonly INFO_FATHER = 'INFO.FATHER';
  static readonly INFO_MOTHER_PARENTS = 'INFO.MOTHER_PARENTS';
  static readonly INFO_FATHER_PARENTS = 'INFO.FATHER_PARENTS';
  static readonly INFO_FIRST_NAME = 'INFO.FIRST_NAME';
  static readonly INFO_MIDDLE_NAME = 'INFO.MIDDLE_NAME';
  static readonly INFO_LAST_NAME = 'INFO.LAST_NAME';
  static readonly INFO_DATE_OF_BIRTH = 'INFO.DATE_OF_BIRTH';
  static readonly INFO_DATE_OF_DEATH = 'INFO.DATE_OF_DEATH';
  static readonly INFO_PHOTO_LABEL = 'INFO.PHOTO_LABEL';
  static readonly INFO_GENDER = 'INFO.GENDER';
  static readonly INFO_FORWARD = 'INFO.FORWARD';
  static readonly INFO_BACK = 'INFO.BACK';
  static readonly INFO_IS_ALIVE = 'INFO.IS_ALIVE';
  static readonly INFO_MATERNAL_GRANDPARENTS = 'INFO.MATERNAL_GRANDPARENTS';
  static readonly INFO_PATERNAL_GRANDPARENTS = 'INFO.PATERNAL_GRANDPARENTS';
  static readonly INFO_MATERNAL_GRANDMOTHER = 'INFO.MATERNAL_GRANDMOTHER';
  static readonly INFO_MATERNAL_GRANDFATHER = 'INFO.MATERNAL_GRANDFATHER';
  static readonly INFO_SAVE = 'INFO.SAVE';
  static readonly INFO_CANCEL = 'INFO.CANCEL';
  static readonly INFO_MEMBER_HEADER = 'INFO.MEMBER_HEADER';
  static readonly INFO_HIDE_LINKS = 'INFO.HIDE_LINKS';
  static readonly INFO_SHOW_LINKS = 'INFO.SHOW_LINKS';
  static readonly INFO_EDIT_MEMBER = 'INFO.EDIT_MEMBER';
  static readonly INFO_ZOOM_IN = 'INFO.ZOOM_IN';
  static readonly INFO_ZOOM_OUT = 'INFO.ZOOM_OUT';
  static readonly INFO_CHANGE_BG = 'INFO.CHANGE_BG';
  static readonly INFO_CHANGE_OPACITY = 'INFO.CHANGE_OPACITY';
  static readonly INFO_CHANGE_PROFILE_IMAGE = 'INFO.CHANGE_PROFILE_IMAGE';
  static readonly INFO_PHOTO_PICKER_HEADER = 'INFO.PHOTO_PICKER_HEADER';
  static readonly INFO_SHOW_CHART = 'INFO.SHOW_CHART';
  static readonly INFO_SHOW_TABLE = 'INFO.SHOW_TABLE';
  static readonly INFO_CHANGE_NODE_SIZE = 'INFO.CHANGE_NODE_SIZE';
  static readonly INFO_FOR_PRINT = 'INFO.FOR_PRINT';
  static readonly INFO_IMAGE_GENERATION = 'INFO.IMAGE_GENERATION';
  static readonly INFO_RELATION_LABEL = 'INFO.RELATION_LABEL';
  static readonly INFO_NAMES = 'INFO.NAMES';
  static readonly INFO_ACTIONS = 'INFO.ACTIONS';
  static readonly INFO_DOB_MODE = 'INFO.DOB_MODE';
  static readonly INFO_DOB_YEAR_ONLY = 'INFO.DOB_YEAR_ONLY';
  static readonly INFO_DOB_NOTE_LABEL = 'INFO.DOB_NOTE_LABEL';
  static readonly INFO_DOD_MODE = 'INFO.DOD_MODE';
  static readonly INFO_DOD_YEAR_ONLY = 'INFO.DOD_YEAR_ONLY';
  static readonly INFO_DOD_NOTE_LABEL = 'INFO.DOD_NOTE_LABEL';
  static readonly INFO_HIDE_BIRTH_DATE = 'INFO.HIDE_BIRTH_DATE';
  static readonly INFO_SHOW_BIRTH_DATE = 'INFO.SHOW_BIRTH_DATE';

  static readonly ADD_PHOTO = 'ADD.PHOTO';

  static readonly GENDER_MALE = 'GENDER.MALE';
  static readonly GENDER_FEMALE = 'GENDER.FEMALE';
  static readonly GENDER_OTHER = 'GENDER.OTHER';

  static readonly RELATION_OWNER = 'RELATION.OWNER';
  static readonly RELATION_MOTHER = 'RELATION.MOTHER';
  static readonly RELATION_FATHER = 'RELATION.FATHER';
  static readonly RELATION_MATERNAL_GRANDMOTHER =
    'RELATION.MATERNAL_GRANDMOTHER';
  static readonly RELATION_MATERNAL_GRANDFATHER =
    'RELATION.MATERNAL_GRANDFATHER';
  static readonly RELATION_PATERNAL_GRANDMOTHER =
    'RELATION.PATERNAL_GRANDMOTHER';
  static readonly RELATION_PATERNAL_GRANDFATHER =
    'RELATION.PATERNAL_GRANDFATHER';

  // Dynamic relations on ANY base
  static readonly RELATION_SON = 'RELATION.SON';
  static readonly RELATION_DAUGHTER = 'RELATION.DAUGHTER';
  static readonly RELATION_BROTHER = 'RELATION.BROTHER';
  static readonly RELATION_SISTER = 'RELATION.SISTER';
  static readonly RELATION_PARTNER = 'RELATION.PARTNER';

  // base + dynamic
  static readonly RELATION_OWNER_SON = 'RELATION.OWNER_SON';
  static readonly RELATION_OWNER_DAUGHTER = 'RELATION.OWNER_DAUGHTER';
  static readonly RELATION_OWNER_BROTHER = 'RELATION.OWNER_BROTHER';
  static readonly RELATION_OWNER_SISTER = 'RELATION.OWNER_SISTER';
  static readonly RELATION_OWNER_PARTNER = 'RELATION.OWNER_PARTNER';

  static readonly RELATION_MOTHER_SON = 'RELATION.MOTHER_SON';
  static readonly RELATION_MOTHER_DAUGHTER = 'RELATION.MOTHER_DAUGHTER';
  static readonly RELATION_MOTHER_BROTHER = 'RELATION.MOTHER_BROTHER';
  static readonly RELATION_MOTHER_SISTER = 'RELATION.MOTHER_SISTER';
  static readonly RELATION_MOTHER_PARTNER = 'RELATION.MOTHER_PARTNER';

  static readonly RELATION_FATHER_SON = 'RELATION.FATHER_SON';
  static readonly RELATION_FATHER_DAUGHTER = 'RELATION.FATHER_DAUGHTER';
  static readonly RELATION_FATHER_BROTHER = 'RELATION.FATHER_BROTHER';
  static readonly RELATION_FATHER_SISTER = 'RELATION.FATHER_SISTER';
  static readonly RELATION_FATHER_PARTNER = 'RELATION.FATHER_PARTNER';

  static readonly RELATION_MATERNAL_GRANDMOTHER_SON =
    'RELATION.MATERNAL_GRANDMOTHER_SON';
  static readonly RELATION_MATERNAL_GRANDMOTHER_DAUGHTER =
    'RELATION.MATERNAL_GRANDMOTHER_DAUGHTER';
  static readonly RELATION_MATERNAL_GRANDMOTHER_BROTHER =
    'RELATION.MATERNAL_GRANDMOTHER_BROTHER';
  static readonly RELATION_MATERNAL_GRANDMOTHER_SISTER =
    'RELATION.MATERNAL_GRANDMOTHER_SISTER';
  static readonly RELATION_MATERNAL_GRANDMOTHER_PARTNER =
    'RELATION.MATERNAL_GRANDMOTHER_PARTNER';

  static readonly RELATION_MATERNAL_GRANDFATHER_SON =
    'RELATION.MATERNAL_GRANDFATHER_SON';
  static readonly RELATION_MATERNAL_GRANDFATHER_DAUGHTER =
    'RELATION.MATERNAL_GRANDFATHER_DAUGHTER';
  static readonly RELATION_MATERNAL_GRANDFATHER_BROTHER =
    'RELATION.MATERNAL_GRANDFATHER_BROTHER';
  static readonly RELATION_MATERNAL_GRANDFATHER_SISTER =
    'RELATION.MATERNAL_GRANDFATHER_SISTER';
  static readonly RELATION_MATERNAL_GRANDFATHER_PARTNER =
    'RELATION.MATERNAL_GRANDFATHER_PARTNER';

  static readonly RELATION_MATERNAL_GRANDMOTHER_FATHER =
    'RELATION.MATERNAL_GRANDMOTHER_FATHER';
  static readonly RELATION_MATERNAL_GRANDMOTHER_MOTHER =
    'RELATION.MATERNAL_GRANDMOTHER_MOTHER';
  static readonly RELATION_MATERNAL_GRANDFATHER_FATHER =
    'RELATION.MATERNAL_GRANDFATHER_FATHER';
  static readonly RELATION_MATERNAL_GRANDFATHER_MOTHER =
    'RELATION.MATERNAL_GRANDFATHER_MOTHER';

  static readonly RELATION_PATERNAL_GRANDMOTHER_SON =
    'RELATION.PATERNAL_GRANDMOTHER_SON';
  static readonly RELATION_PATERNAL_GRANDMOTHER_DAUGHTER =
    'RELATION.PATERNAL_GRANDMOTHER_DAUGHTER';
  static readonly RELATION_PATERNAL_GRANDMOTHER_BROTHER =
    'RELATION.PATERNAL_GRANDMOTHER_BROTHER';
  static readonly RELATION_PATERNAL_GRANDMOTHER_SISTER =
    'RELATION.PATERNAL_GRANDMOTHER_SISTER';
  static readonly RELATION_PATERNAL_GRANDMOTHER_PARTNER =
    'RELATION.PATERNAL_GRANDMOTHER_PARTNER';

  static readonly RELATION_PATERNAL_GRANDFATHER_SON =
    'RELATION.PATERNAL_GRANDFATHER_SON';
  static readonly RELATION_PATERNAL_GRANDFATHER_DAUGHTER =
    'RELATION.PATERNAL_GRANDFATHER_DAUGHTER';
  static readonly RELATION_PATERNAL_GRANDFATHER_BROTHER =
    'RELATION.PATERNAL_GRANDFATHER_BROTHER';
  static readonly RELATION_PATERNAL_GRANDFATHER_SISTER =
    'RELATION.PATERNAL_GRANDFATHER_SISTER';
  static readonly RELATION_PATERNAL_GRANDFATHER_PARTNER =
    'RELATION.PATERNAL_GRANDFATHER_PARTNER';

  static readonly RELATION_PATERNAL_GRANDMOTHER_FATHER =
    'RELATION.PATERNAL_GRANDMOTHER_FATHER';
  static readonly RELATION_PATERNAL_GRANDMOTHER_MOTHER =
    'RELATION.PATERNAL_GRANDMOTHER_MOTHER';
  static readonly RELATION_PATERNAL_GRANDFATHER_FATHER =
    'RELATION.PATERNAL_GRANDFATHER_FATHER';
  static readonly RELATION_PATERNAL_GRANDFATHER_MOTHER =
    'RELATION.PATERNAL_GRANDFATHER_MOTHER';

  // Headers/buttons
  static readonly RELATION_ADD_RELATIVE_HEADER = 'RELATION.ADD_RELATIVE_HEADER';
  static readonly RELATION_CHOOSE_RELATION = 'RELATION.CHOOSE_RELATION';

  // Generic fallbacks
  static readonly RELATION_MATERNAL_GENERIC = 'RELATION.MATERNAL_GENERIC';
  static readonly RELATION_PATERNAL_GENERIC = 'RELATION.PATERNAL_GENERIC';
  static readonly RELATION_UNKNOWN = 'RELATION.UNKNOWN';
  static readonly RELATION_TYPE = 'RELATION.TYPE';

  static readonly TAB_GENERAL_INFO = 'TAB.GENERAL_INFO';
  static readonly TAB_RELATIONS = 'TAB.RELATIONS';
  static readonly TAB_BIOGRAPHY = 'TAB.BIOGRAPHY';
  static readonly TAB_MEDIA = 'TAB.MEDIA';
  static readonly TAB_CAREER = 'TAB.CAREER';
  static readonly TAB_ACHIEVEMENTS = 'TAB.ACHIEVEMENTS';
  static readonly TAB_FAVORITES = 'TAB.FAVORITES';
  static readonly TAB_PERSONAL_INFO = 'TAB.PERSONAL_INFO';

  static readonly PARTNER_STATUS_MARRIED = 'PARTNER_STATUS.MARRIED';
  static readonly PARTNER_STATUS_DIVORCED = 'PARTNER_STATUS.DIVORCED';
  static readonly PARTNER_STATUS_SEPARATED = 'PARTNER_STATUS.SEPARATED';
  static readonly PARTNER_STATUS_WIDOWED = 'PARTNER_STATUS.WIDOWED';
  static readonly PARTNER_STATUS_ENGAGED = 'PARTNER_STATUS.ENGAGED';
  static readonly PARTNER_STATUS_PARTNERS = 'PARTNER_STATUS.PARTNERS';
  static readonly PARTNER_STATUS_FRIENDS = 'PARTNER_STATUS.FRIENDS';
  static readonly PARTNER_STATUS_ANNULLED = 'PARTNER_STATUS.ANNULLED';
  static readonly PARTNER_STATUS_UNKNOWN = 'PARTNER_STATUS.UNKNOWN';
  static readonly PARTNER_STATUS_OTHER = 'PARTNER_STATUS.OTHER';
}
