export class CONSTANTS {
  static readonly AUTH_PROFILE = 'AUTH.PROFILE';
  static readonly AUTH_LOGOUT = 'AUTH.LOGOUT';
  static readonly AUTH_LOGIN = 'AUTH.LOGIN';
  static readonly AUTH_REGISTER = 'AUTH.REGISTER';
  static readonly AUTH_EMAIL = 'AUTH.EMAIL';
  static readonly AUTH_PASSWORD = 'AUTH.PASSWORD';
  static readonly AUTH_CONFIRM_PASSWORD = 'AUTH.CONFIRM_PASSWORD';
  static readonly AUTH_LOGIN_IN_PROFILE = 'AUTH.LOGIN_IN_PROFILE';
  static readonly AUTH_ALREADY_REGISTERED = 'AUTH.ALREADY_REGISTERED';
  static readonly AUTH_PASSWORDS_NOT_MATCH = 'AUTH.PASSWORDS_NOT_MATCH';
  static readonly AUTH_REGISTER_FAILED = 'AUTH.REGISTER_FAILED';
  static readonly AUTH_LOGIN_FAILED = 'AUTH.LOGIN_FAILED';
  static readonly AUTH_NO_ACCOUNT = 'AUTH.NO_ACCOUNT';
  static readonly AUTH_REGISTER_NOW = 'AUTH.REGISTER_NOW';
  static readonly AUTH_GOOGLE_LOGIN = 'AUTH.GOOGLE_LOGIN';
  static readonly AUTH_SETTINGS = 'AUTH.SETTINGS';
  static readonly AUTH_ACCOUNT_SETTINGS = 'AUTH.ACCOUNT_SETTINGS';
  static readonly AUTH_SUBSCRIPTION_SETTINGS = 'AUTH.SUBSCRIPTION_SETTINGS';
  static readonly AUTH_PRIVACY_SETTINGS = 'AUTH.PRIVACY_SETTINGS';
  static readonly AUTH_LOGIN_ERROR = 'AUTH.LOGIN_ERROR';
  static readonly AUTH_PASSWORD_PROMPT = 'AUTH.PASSWORD_PROMPT';
  static readonly AUTH_PASSWORD_WEAK = 'AUTH.PASSWORD_WEAK';
  static readonly AUTH_PASSWORD_MEDIUM = 'AUTH.PASSWORD_MEDIUM';
  static readonly AUTH_PASSWORD_STRONG = 'AUTH.PASSWORD_STRONG';
  static readonly AUTH_RESET_PASSWORD = 'AUTH.RESET_PASSWORD';
  static readonly AUTH_RULE_LOWER = 'AUTH.RULE_LOWER';
  static readonly AUTH_RULE_UPPER = 'AUTH.RULE_UPPER';
  static readonly AUTH_RULE_NUMBER = 'AUTH.RULE_NUMBER';
  static readonly AUTH_RULE_SPECIAL = 'AUTH.RULE_SPECIAL';
  static readonly AUTH_RULE_MIN10 = 'AUTH.RULE_MIN10';
  static readonly AUTH_PASSWORD_RULES_MSG = 'AUTH.PASSWORD_RULES_MSG';
  static readonly AUTH_ERROR_CURRENT_PASSWORD = 'AUTH.ERROR_CURRENT_PASSWORD';
  static readonly AUTH_ERROR_PASSWORD_SAME = 'AUTH.ERROR_PASSWORD_SAME';
  static readonly AUTH_FORGOT_PASSWORD = 'AUTH.FORGOT_PASSWORD';
  static readonly AUTH_SEND_RESET_LINK = 'AUTH.SEND_RESET_LINK';
  static readonly AUTH_RESET_LINK_SENT_GENERIC = 'AUTH.RESET_LINK_SENT_GENERIC';
  static readonly AUTH_SAVE_NEW_PASSWORD = 'AUTH.SAVE_NEW_PASSWORD';
  static readonly AUTH_PASSWORD_UPDATED = 'AUTH.PASSWORD_UPDATED';
  static readonly AUTH_RESET_ERROR = 'AUTH.RESET_ERROR';

  static readonly ACCOUNT_PAGE_TITLE = 'ACCOUNT.PAGE_TITLE';
  static readonly ACCOUNT_PAGE_SUBTITLE = 'ACCOUNT.PAGE_SUBTITLE';
  static readonly ACCOUNT_SECTION_PROFILE = 'ACCOUNT.SECTION_PROFILE';
  static readonly ACCOUNT_SECTION_PROFILE_DESC =
    'ACCOUNT.SECTION_PROFILE_DESC';
  static readonly ACCOUNT_DISPLAY_NAME = 'ACCOUNT.DISPLAY_NAME';
  static readonly ACCOUNT_EMAIL = 'ACCOUNT.EMAIL';
  static readonly ACCOUNT_MEMBER_SINCE = 'ACCOUNT.MEMBER_SINCE';
  static readonly ACCOUNT_LAST_UPDATED = 'ACCOUNT.LAST_UPDATED';
  static readonly ACCOUNT_SIGNIN_METHOD = 'ACCOUNT.SIGNIN_METHOD';
  static readonly ACCOUNT_SIGNIN_METHOD_LOCAL = 'ACCOUNT.SIGNIN_METHOD_LOCAL';
  static readonly ACCOUNT_SIGNIN_METHOD_GOOGLE = 'ACCOUNT.SIGNIN_METHOD_GOOGLE';
  static readonly ACCOUNT_SAVE_PROFILE = 'ACCOUNT.SAVE_PROFILE';
  static readonly ACCOUNT_PROFILE_UPDATED = 'ACCOUNT.PROFILE_UPDATED';
  static readonly ACCOUNT_PROFILE_UPDATE_ERROR =
    'ACCOUNT.PROFILE_UPDATE_ERROR';
  static readonly ACCOUNT_SECTION_LANGUAGE = 'ACCOUNT.SECTION_LANGUAGE';
  static readonly ACCOUNT_SECTION_LANGUAGE_DESC =
    'ACCOUNT.SECTION_LANGUAGE_DESC';
  static readonly ACCOUNT_SAVE_LANGUAGE = 'ACCOUNT.SAVE_LANGUAGE';
  static readonly ACCOUNT_LANGUAGE_UPDATED = 'ACCOUNT.LANGUAGE_UPDATED';
  static readonly ACCOUNT_LANGUAGE_UPDATE_ERROR =
    'ACCOUNT.LANGUAGE_UPDATE_ERROR';
  static readonly ACCOUNT_SECTION_SECURITY = 'ACCOUNT.SECTION_SECURITY';
  static readonly ACCOUNT_SECTION_SECURITY_DESC =
    'ACCOUNT.SECTION_SECURITY_DESC';
  static readonly ACCOUNT_CURRENT_PASSWORD = 'ACCOUNT.CURRENT_PASSWORD';
  static readonly ACCOUNT_NEW_PASSWORD = 'ACCOUNT.NEW_PASSWORD';
  static readonly ACCOUNT_CONFIRM_NEW_PASSWORD =
    'ACCOUNT.CONFIRM_NEW_PASSWORD';
  static readonly ACCOUNT_SAVE_PASSWORD = 'ACCOUNT.SAVE_PASSWORD';
  static readonly ACCOUNT_PASSWORD_UPDATED = 'ACCOUNT.PASSWORD_UPDATED';
  static readonly ACCOUNT_PASSWORD_UPDATE_ERROR =
    'ACCOUNT.PASSWORD_UPDATE_ERROR';
  static readonly ACCOUNT_PASSWORD_UNAVAILABLE_TITLE =
    'ACCOUNT.PASSWORD_UNAVAILABLE_TITLE';
  static readonly ACCOUNT_PASSWORD_UNAVAILABLE_DESC =
    'ACCOUNT.PASSWORD_UNAVAILABLE_DESC';
  static readonly ACCOUNT_DELETE_TITLE = 'ACCOUNT.DELETE_TITLE';
  static readonly ACCOUNT_DELETE_DESC = 'ACCOUNT.DELETE_DESC';
  static readonly ACCOUNT_DELETE_BUTTON = 'ACCOUNT.DELETE_BUTTON';
  static readonly ACCOUNT_DELETE_DIALOG_TITLE = 'ACCOUNT.DELETE_DIALOG_TITLE';
  static readonly ACCOUNT_DELETE_DIALOG_MESSAGE =
    'ACCOUNT.DELETE_DIALOG_MESSAGE';
  static readonly ACCOUNT_DELETE_DIALOG_WARNING =
    'ACCOUNT.DELETE_DIALOG_WARNING';
  static readonly ACCOUNT_DELETE_CONFIRM = 'ACCOUNT.DELETE_CONFIRM';
  static readonly ACCOUNT_DELETE_CANCEL = 'ACCOUNT.DELETE_CANCEL';
  static readonly ACCOUNT_DELETE_ERROR = 'ACCOUNT.DELETE_ERROR';

  static readonly PRIVACY_PAGE_TITLE = 'PRIVACY_SETTINGS.PAGE_TITLE';
  static readonly PRIVACY_PAGE_SUBTITLE = 'PRIVACY_SETTINGS.PAGE_SUBTITLE';
  static readonly PRIVACY_DEFAULTS_EYEBROW = 'PRIVACY_SETTINGS.DEFAULTS_EYEBROW';
  static readonly PRIVACY_DEFAULTS_TITLE = 'PRIVACY_SETTINGS.DEFAULTS_TITLE';
  static readonly PRIVACY_DEFAULTS_DESC = 'PRIVACY_SETTINGS.DEFAULTS_DESC';
  static readonly PRIVACY_DEFAULTS_DISCOVERY =
    'PRIVACY_SETTINGS.DEFAULTS_DISCOVERY';
  static readonly PRIVACY_DEFAULTS_DISCOVERY_DESC =
    'PRIVACY_SETTINGS.DEFAULTS_DISCOVERY_DESC';
  static readonly PRIVACY_DEFAULTS_DETAILS =
    'PRIVACY_SETTINGS.DEFAULTS_DETAILS';
  static readonly PRIVACY_DEFAULTS_DETAILS_DESC =
    'PRIVACY_SETTINGS.DEFAULTS_DETAILS_DESC';
  static readonly PRIVACY_ADMIN_ACCESS = 'PRIVACY_SETTINGS.ADMIN_ACCESS';
  static readonly PRIVACY_ADMIN_ACCESS_DESC =
    'PRIVACY_SETTINGS.ADMIN_ACCESS_DESC';
  static readonly PRIVACY_DEFAULTS_RESET = 'PRIVACY_SETTINGS.DEFAULTS_RESET';
  static readonly PRIVACY_DEFAULTS_SUCCESS = 'PRIVACY_SETTINGS.DEFAULTS_SUCCESS';
  static readonly PRIVACY_DEFAULTS_ERROR = 'PRIVACY_SETTINGS.DEFAULTS_ERROR';
  static readonly PRIVACY_COOKIES_EYEBROW = 'PRIVACY_SETTINGS.COOKIES_EYEBROW';
  static readonly PRIVACY_COOKIES_TITLE = 'PRIVACY_SETTINGS.COOKIES_TITLE';
  static readonly PRIVACY_COOKIES_DESC = 'PRIVACY_SETTINGS.COOKIES_DESC';
  static readonly PRIVACY_COOKIES_UPDATED = 'PRIVACY_SETTINGS.COOKIES_UPDATED';
  static readonly PRIVACY_COOKIES_NEVER = 'PRIVACY_SETTINGS.COOKIES_NEVER';
  static readonly PRIVACY_COOKIES_ANALYTICS =
    'PRIVACY_SETTINGS.COOKIES_ANALYTICS';
  static readonly PRIVACY_COOKIES_ANALYTICS_DESC =
    'PRIVACY_SETTINGS.COOKIES_ANALYTICS_DESC';
  static readonly PRIVACY_COOKIES_MARKETING =
    'PRIVACY_SETTINGS.COOKIES_MARKETING';
  static readonly PRIVACY_COOKIES_MARKETING_DESC =
    'PRIVACY_SETTINGS.COOKIES_MARKETING_DESC';
  static readonly PRIVACY_COOKIES_SAVE = 'PRIVACY_SETTINGS.COOKIES_SAVE';
  static readonly PRIVACY_COOKIES_SUCCESS = 'PRIVACY_SETTINGS.COOKIES_SUCCESS';
  static readonly PRIVACY_COOKIES_ERROR = 'PRIVACY_SETTINGS.COOKIES_ERROR';
  static readonly PRIVACY_SHORTCUTS_EYEBROW =
    'PRIVACY_SETTINGS.SHORTCUTS_EYEBROW';
  static readonly PRIVACY_SHORTCUTS_TITLE = 'PRIVACY_SETTINGS.SHORTCUTS_TITLE';
  static readonly PRIVACY_SHORTCUTS_DESC = 'PRIVACY_SETTINGS.SHORTCUTS_DESC';
  static readonly PRIVACY_SHORTCUTS_POLICY =
    'PRIVACY_SETTINGS.SHORTCUTS_POLICY';
  static readonly PRIVACY_SHORTCUTS_COOKIES =
    'PRIVACY_SETTINGS.SHORTCUTS_COOKIES';
  static readonly PRIVACY_SHORTCUTS_SHARING =
    'PRIVACY_SETTINGS.SHORTCUTS_SHARING';
  static readonly PRIVACY_SHORTCUTS_SUPPORT =
    'PRIVACY_SETTINGS.SHORTCUTS_SUPPORT';
  static readonly PRIVACY_SHORTCUTS_SUPPORT_DESC =
    'PRIVACY_SETTINGS.SHORTCUTS_SUPPORT_DESC';

  static readonly COMMON_APP_NAME = 'COMMON.APP_NAME';
  static readonly COMMON_APP_NAME_PERSONALIZED = 'COMMON.APP_NAME_PERSONALIZED';
  static readonly COMMON_LANGUAGE = 'COMMON.LANGUAGE';
  static readonly COMMON_LANG_BG = 'COMMON.LANG_BG';
  static readonly COMMON_LANG_EN = 'COMMON.LANG_EN';
  static readonly COMMON_MOBILE_HINT_TITLE = 'COMMON.MOBILE_HINT_TITLE';
  static readonly COMMON_MOBILE_HINT_MESSAGE = 'COMMON.MOBILE_HINT_MESSAGE';
  static readonly COMMON_FAQ = 'COMMON.FAQ';
  static readonly COMMON_SETTINGS = 'COMMON.SETTINGS';
  static readonly COMMON_CURRENCY_EUR = 'COMMON.CURRENCY_EUR';
  static readonly COMMON_CONTACT_US = 'COMMON.CONTACT_US';
  static readonly COMMON_VALIDATION = 'COMMON.VALIDATION';
  static readonly COMMON_ERROR = 'COMMON.ERROR';
  static readonly COMMON_MEMBER = 'COMMON.MEMBER';
  static readonly ERROR_PARENT_EXISTS_MOTHER = 'COMMON.PARENT_EXISTS_MOTHER';
  static readonly ERROR_PARENT_EXISTS_FATHER = 'COMMON.PARENT_EXISTS_FATHER';
  static readonly COMMON_RECAPTCHA_FAILED = 'COMMON.RECAPTCHA_FAILED';
  static readonly COMMON_RECAPTCHA_NOTICE = 'COMMON.RECAPTCHA_NOTICE';

  static readonly FAQ_TITLE = 'FAQ.TITLE';
  static readonly FAQ_INTRO = 'FAQ.INTRO';
  static readonly FAQ_Q_WHAT_IS_APP = 'FAQ.Q.WHAT_IS_APP';
  static readonly FAQ_A_WHAT_IS_APP = 'FAQ.A.WHAT_IS_APP';
  static readonly FAQ_Q_HOW_ADD_FAMILY = 'FAQ.Q.HOW_ADD_FAMILY';
  static readonly FAQ_A_HOW_ADD_FAMILY = 'FAQ.A.HOW_ADD_FAMILY';
  static readonly FAQ_Q_MEDIA_LIMITS = 'FAQ.Q.MEDIA_LIMITS';
  static readonly FAQ_A_MEDIA_LIMITS = 'FAQ.A.MEDIA_LIMITS';
  static readonly FAQ_Q_SUBSCRIPTIONS = 'FAQ.Q.SUBSCRIPTIONS';
  static readonly FAQ_A_SUBSCRIPTIONS = 'FAQ.A.SUBSCRIPTIONS';
  static readonly FAQ_Q_PRIVACY = 'FAQ.Q.PRIVACY';
  static readonly FAQ_A_PRIVACY = 'FAQ.A.PRIVACY';
  static readonly FAQ_Q_MEMBERS_MANAGE = 'FAQ.Q.MEMBERS_MANAGE';
  static readonly FAQ_A_MEMBERS_MANAGE = 'FAQ.A.MEMBERS_MANAGE';
  static readonly FAQ_Q_GLOBAL_SEARCH = 'FAQ.Q.GLOBAL_SEARCH';
  static readonly FAQ_A_GLOBAL_SEARCH = 'FAQ.A.GLOBAL_SEARCH';
  static readonly FAQ_Q_SHARING_SETTINGS = 'FAQ.Q.SHARING_SETTINGS';
  static readonly FAQ_A_SHARING_SETTINGS = 'FAQ.A.SHARING_SETTINGS';
  static readonly FAQ_Q_SHARING_REQUESTS = 'FAQ.Q.SHARING_REQUESTS';
  static readonly FAQ_A_SHARING_REQUESTS = 'FAQ.A.SHARING_REQUESTS';
  static readonly FAQ_Q_GDPR = 'FAQ.Q.GDPR';
  static readonly FAQ_A_GDPR = 'FAQ.A.GDPR';

  static readonly ROUTES = {
    HOME: '',
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    AUTH_FORGOT: '/auth/forgot',
    TREE: '/tree',
    MEMBER: '/member',
    SEARCH: '/search',
    AUTH_GOOGLE_LOGIN: '/auth/google',
    FAMILY_MEMBERS: 'family-members',
    ACCOUNT: {
      MY_ACCOUNT: '/account/my-account',
      SUBSCRIPTION: '/account/subscription',
      PRIVACY: '/account/privacy',
    },
    SUBSCRIPTION: {
      PAYMENT: '/subscription/payment',
    },
    SETTINGS: {
      SUBSCRIPTION_PLANS: '/settings/plans',
      SHARING: '/settings/sharing',
    },
    SHARING: {
      REQUESTS: '/sharing/requests',
    },
    ONBOARDING: {
      OWNER: '/onboarding/owner',
      MOTHER: '/onboarding/mother',
      MATERNAL_GRANDPARENTS: '/onboarding/maternal-grandparents',
      FATHER: '/onboarding/father',
      PATERNAL_GRANDPARENTS: '/onboarding/paternal-grandparents',
      SUBSCRIPTION: '/onboarding/subscription',
    },
    CONTACT: '/contact',
    SUPPORT: '/support',
    LEGAL: {
      PRIVACY: '/privacy',
      COOKIES: '/cookies',
    },
    FAQ: '/faq',
    ADMIN: '/admin',
  };

  static readonly COMMON_NAME = 'COMMON.NAME';
  static readonly COMMON_YEARS = 'COMMON.YEARS';
  static readonly COMMON_STATUS = 'COMMON.STATUS';
  static readonly COMMON_ACTIONS = 'COMMON.ACTIONS';
  static readonly COMMON_MESSAGE = 'COMMON.MESSAGE';
  static readonly COMMON_CREATED_AT = 'COMMON.CREATED_AT';
  static readonly COMMON_SAVE = 'COMMON.SAVE';
  static readonly COMMON_APPROVE = 'COMMON.APPROVE';
  static readonly COMMON_REJECT = 'COMMON.REJECT';
  static readonly COMMON_OWNER = 'COMMON.OWNER';
  static readonly COMMON_OPTIONAL = 'COMMON.OPTIONAL';
  static readonly COMMON_PRIVACY_POLICY = 'COMMON.PRIVACY_POLICY';
  static readonly COMMON_COOKIE_POLICY = 'COMMON.COOKIE_POLICY';
  static readonly COMMON_RIGHTS_RESERVED = 'COMMON.RIGHTS_RESERVED';
  static readonly COMMON_FOOTER_TAGLINE = 'COMMON.FOOTER_TAGLINE';
  static readonly COMMON_FOLLOW_US = 'COMMON.FOLLOW_US';
  static readonly COMMON_SUPPORT_US = 'COMMON.SUPPORT_US';
  static readonly COMMON_LEGAL = 'COMMON.LEGAL';
  static readonly SUBSCRIPTION_PLAN_UPDATED = 'SUBSCRIPTION.PLAN_UPDATED';
  static readonly SUBSCRIPTION_PLAN_ACTIVE = 'SUBSCRIPTION.PLAN_ACTIVE';
  static readonly SUBSCRIPTION_PLAN_UPDATE_ERROR =
    'SUBSCRIPTION.PLAN_UPDATE_ERROR';
  static readonly SUBSCRIPTION_SETTINGS_TITLE =
    'SUBSCRIPTION.SETTINGS_TITLE';
  static readonly SUBSCRIPTION_SETTINGS_CURRENT =
    'SUBSCRIPTION.CURRENT_PLAN';
  static readonly SUBSCRIPTION_SETTINGS_NONE = 'SUBSCRIPTION.NO_PLAN';
  static readonly SUBSCRIPTION_SETTINGS_EXPIRES =
    'SUBSCRIPTION.EXPIRES_ON';
  static readonly SUBSCRIPTION_SETTINGS_CHANGE =
    'SUBSCRIPTION.CHANGE_PLAN';
  static readonly SUBSCRIPTION_SETTINGS_LIMITS =
    'SUBSCRIPTION.LIMITS';
  static readonly SUBSCRIPTION_SETTINGS_RENEWAL =
    'SUBSCRIPTION.SETTINGS_RENEWAL';
  static readonly SUBSCRIPTION_PAYMENT_TITLE =
    'SUBSCRIPTION.PAYMENT_TITLE';
  static readonly SUBSCRIPTION_PAYMENT_DESC =
    'SUBSCRIPTION.PAYMENT_DESC';
  static readonly SUBSCRIPTION_PAYMENT_SUMMARY =
    'SUBSCRIPTION.PAYMENT_SUMMARY';
  static readonly SUBSCRIPTION_PAYMENT_TOTAL =
    'SUBSCRIPTION.PAYMENT_TOTAL';
  static readonly SUBSCRIPTION_PAYMENT_PER_DAY =
    'SUBSCRIPTION.PAYMENT_PER_DAY';
    static readonly SUBSCRIPTION_PAYMENT_FORM_TITLE =
      'SUBSCRIPTION.PAYMENT_FORM_TITLE';
    static readonly SUBSCRIPTION_PAYMENT_CARD_NAME =
      'SUBSCRIPTION.PAYMENT_CARD_NAME';
  static readonly SUBSCRIPTION_PAYMENT_CARD_NUMBER =
    'SUBSCRIPTION.PAYMENT_CARD_NUMBER';
  static readonly SUBSCRIPTION_PAYMENT_EXPIRY =
    'SUBSCRIPTION.PAYMENT_EXPIRY';
    static readonly SUBSCRIPTION_PAYMENT_CVC =
      'SUBSCRIPTION.PAYMENT_CVC';
    static readonly SUBSCRIPTION_PAYMENT_SUBMIT =
      'SUBSCRIPTION.PAYMENT_SUBMIT';
    static readonly SUBSCRIPTION_PAYMENT_PROVIDER_TITLE =
      'SUBSCRIPTION.PAYMENT_PROVIDER_TITLE';
    static readonly SUBSCRIPTION_PAYMENT_PROVIDER_NOTE =
      'SUBSCRIPTION.PAYMENT_PROVIDER_NOTE';
    static readonly SUBSCRIPTION_PAYMENT_PROVIDER_SECURE =
      'SUBSCRIPTION.PAYMENT_PROVIDER_SECURE';
    static readonly SUBSCRIPTION_PAYMENT_PROVIDER_SUPPORT =
      'SUBSCRIPTION.PAYMENT_PROVIDER_SUPPORT';
    static readonly SUBSCRIPTION_PAYMENT_REDIRECT =
      'SUBSCRIPTION.PAYMENT_REDIRECT';
    static readonly SUBSCRIPTION_PAYMENT_NOT_CONFIGURED =
      'SUBSCRIPTION.PAYMENT_NOT_CONFIGURED';
    static readonly SUBSCRIPTION_PAYMENT_CANCELED =
      'SUBSCRIPTION.PAYMENT_CANCELED';
    static readonly SUBSCRIPTION_PAYMENT_RETRY =
      'SUBSCRIPTION.PAYMENT_RETRY';
    static readonly SUBSCRIPTION_PAYMENT_SUCCESS =
      'SUBSCRIPTION.PAYMENT_SUCCESS';
  static readonly SUBSCRIPTION_PAYMENT_ERROR =
    'SUBSCRIPTION.PAYMENT_ERROR';
  static readonly SUBSCRIPTION_PAYMENT_TERMS =
    'SUBSCRIPTION.PAYMENT_TERMS';
  static readonly SUBSCRIPTION_PAYMENT_BACK =
    'SUBSCRIPTION.PAYMENT_BACK';
  static readonly SUBSCRIPTION_LIMIT_TITLE =
    'SUBSCRIPTION.LIMIT_TITLE';
  static readonly SUBSCRIPTION_LIMIT_MESSAGE =
    'SUBSCRIPTION.LIMIT_MESSAGE';
  static readonly SUBSCRIPTION_LIMIT_CTA =
    'SUBSCRIPTION.LIMIT_CTA';
  static readonly ONBOARDING_SUBSCRIPTION_TITLE =
    'ONBOARDING.SUBSCRIPTION.TITLE';
  static readonly ONBOARDING_SUBSCRIPTION_DESC =
    'ONBOARDING.SUBSCRIPTION.DESC';
  static readonly ONBOARDING_SUBSCRIPTION_PER_DAY =
    'ONBOARDING.SUBSCRIPTION.PER_DAY';
  static readonly ONBOARDING_SUBSCRIPTION_DURATION =
    'ONBOARDING.SUBSCRIPTION.DURATION';
  static readonly ONBOARDING_SUBSCRIPTION_MONTHS =
    'ONBOARDING.SUBSCRIPTION.MONTHS';
  static readonly ONBOARDING_SUBSCRIPTION_SKIP =
    'ONBOARDING.SUBSCRIPTION.SKIP';
  static readonly ONBOARDING_SUBSCRIPTION_LIMITS =
    'ONBOARDING.SUBSCRIPTION.LIMITS';
  static readonly COMMON_SEND = 'COMMON.SEND';
  static readonly COMMON_CONFIRM = 'COMMON.CONFIRM';
  static readonly SUPPORT_TITLE = 'SUPPORT.TITLE';
  static readonly SUPPORT_INTRO = 'SUPPORT.INTRO';
  static readonly SUPPORT_MISSION = 'SUPPORT.MISSION';
  static readonly SUPPORT_VALUES = 'SUPPORT.VALUES';
  static readonly SUPPORT_DONATION_TEXT = 'SUPPORT.DONATION_TEXT';
  static readonly SUPPORT_HOW_TITLE = 'SUPPORT.HOW_TITLE';
  static readonly SUPPORT_REASON_PRESERVE = 'SUPPORT.REASONS.PRESERVE';
  static readonly SUPPORT_REASON_FUTURE = 'SUPPORT.REASONS.FUTURE';
  static readonly SUPPORT_REASON_COMMUNITY = 'SUPPORT.REASONS.COMMUNITY';
  static readonly SUPPORT_CONTACT = 'SUPPORT.CONTACT';
  static readonly SUPPORT_EMAIL_CTA = 'SUPPORT.EMAIL_CTA';
  static readonly SUPPORT_THANK_YOU = 'SUPPORT.THANK_YOU';
  static readonly SUPPORT_DONATION_TITLE = 'SUPPORT.DONATION_TITLE';
  static readonly SUPPORT_DONATION_LEAD = 'SUPPORT.DONATION_LEAD';
  static readonly SUPPORT_AMOUNT_LABEL = 'SUPPORT.AMOUNT_LABEL';
  static readonly SUPPORT_MESSAGE_LABEL = 'SUPPORT.MESSAGE_LABEL';
  static readonly SUPPORT_MESSAGE_PLACEHOLDER = 'SUPPORT.MESSAGE_PLACEHOLDER';
  static readonly SUPPORT_AMOUNT_MIN = 'SUPPORT.AMOUNT_MIN';
  static readonly SUPPORT_DONATION_SUBMIT = 'SUPPORT.DONATION_SUBMIT';
  static readonly SUPPORT_DONATION_PROVIDER_NOTE =
    'SUPPORT.DONATION_PROVIDER_NOTE';
  static readonly SUPPORT_DONATION_ERROR = 'SUPPORT.DONATION_ERROR';
  static readonly SUPPORT_STRIPE_MISSING = 'SUPPORT.STRIPE_MISSING';
  static readonly SUPPORT_DONATION_SUCCESS = 'SUPPORT.DONATION_SUCCESS';
  static readonly SUPPORT_DONATION_CANCELED = 'SUPPORT.DONATION_CANCELED';
  static readonly SUPPORT_DONATION_RETRY = 'SUPPORT.DONATION_RETRY';

  static readonly SEARCH_PLACEHOLDER = 'SEARCH.PLACEHOLDER';
  static readonly SEARCH_PUBLIC = 'SEARCH.PUBLIC';
  static readonly SEARCH_REQUIRES_REQUEST = 'SEARCH.REQUIRES_REQUEST';
  static readonly SEARCH_IMPORT_AND_ADD = 'SEARCH.IMPORT_AND_ADD';
  static readonly SEARCH_REQUEST_ACCESS = 'SEARCH.REQUEST_ACCESS';
  static readonly SEARCH_REQUEST_PENDING = 'SEARCH.REQUEST_PENDING';
  static readonly SEARCH_REQUEST_ERROR = 'SEARCH.REQUEST_ERROR';

  static readonly SHARING_SETTINGS_TITLE = 'SHARING.SETTINGS_TITLE';
  static readonly SHARING_DEFAULTS = 'SHARING.DEFAULTS';
  static readonly SHARING_ALLOW_DISCOVERY_DEFAULT =
    'SHARING.ALLOW_DISCOVERY_DEFAULT';
  static readonly SHARING_ALLOW_DETAILS_DEFAULT =
    'SHARING.ALLOW_DETAILS_DEFAULT';
  static readonly SHARING_PER_MEMBER = 'SHARING.PER_MEMBER';
  static readonly SHARING_ALLOW_DISCOVERY = 'SHARING.ALLOW_DISCOVERY';
  static readonly SHARING_ALLOW_DETAILS = 'SHARING.ALLOW_DETAILS';
  static readonly SHARING_INCOMING = 'SHARING.INCOMING';
  static readonly SHARING_OUTGOING = 'SHARING.OUTGOING';
  static readonly SHARING_TARGET = 'SHARING.TARGET';
  static readonly SHARING_REQUESTER = 'SHARING.REQUESTER';
  static readonly SHARING_REQUESTS_MENU = 'SHARING.REQUESTS_MENU';
  static readonly SHARING_USE_IMPORTED = 'SHARING.USE_IMPORTED';
  static readonly SHARING_SELECT_IMPORTED = 'SHARING.SELECT_IMPORTED';
  static readonly SHARING_APPROVED = 'SHARING.APPROVED';
  static readonly SHARING_STATUS_PENDING = 'SHARING.STATUS_PENDING';
  static readonly SHARING_STATUS_APPROVED = 'SHARING.STATUS_APPROVED';
  static readonly SHARING_STATUS_REJECTED = 'SHARING.STATUS_REJECTED';
  static readonly SHARING_CONFIRM_APPROVE_TITLE = 'SHARING.CONFIRM_APPROVE_TITLE';
  static readonly SHARING_CONFIRM_APPROVE_MESSAGE = 'SHARING.CONFIRM_APPROVE_MESSAGE';
  static readonly SHARING_CONFIRM_REJECT_TITLE = 'SHARING.CONFIRM_REJECT_TITLE';
  static readonly SHARING_CONFIRM_REJECT_MESSAGE = 'SHARING.CONFIRM_REJECT_MESSAGE';
  static readonly SHARING_CONFIRM_IMPORT_TITLE = 'SHARING.CONFIRM_IMPORT_TITLE';
  static readonly SHARING_CONFIRM_IMPORT_MESSAGE = 'SHARING.CONFIRM_IMPORT_MESSAGE';
  static readonly SHARING_INFO_TOOLTIP = 'SHARING.INFO_TOOLTIP';
  static readonly SHARING_INFO_ARIA = 'SHARING.INFO_ARIA';

  static readonly INFO_OWNER = 'INFO.OWNER';
  static readonly INFO_MOTHER = 'INFO.MOTHER';
  static readonly INFO_FATHER = 'INFO.FATHER';
  static readonly INFO_MOTHER_PARENTS = 'INFO.MOTHER_PARENTS';
  static readonly INFO_FATHER_PARENTS = 'INFO.FATHER_PARENTS';
  static readonly INFO_FIRST_NAME = 'INFO.FIRST_NAME';
  static readonly INFO_MIDDLE_NAME = 'INFO.MIDDLE_NAME';
  static readonly INFO_LAST_NAME = 'INFO.LAST_NAME';
  static readonly INFO_DATE_OF_BIRTH = 'INFO.DATE_OF_BIRTH';
  static readonly INFO_DATE_OF_DEATH = 'INFO.DATE_OF_DEATH';
  static readonly INFO_PHOTO_LABEL = 'INFO.PHOTO_LABEL';
  static readonly INFO_GENDER = 'INFO.GENDER';
  static readonly INFO_FORWARD = 'INFO.FORWARD';
  static readonly INFO_BACK = 'INFO.BACK';
  static readonly INFO_IS_ALIVE = 'INFO.IS_ALIVE';
  static readonly INFO_MATERNAL_GRANDPARENTS = 'INFO.MATERNAL_GRANDPARENTS';
  static readonly INFO_PATERNAL_GRANDPARENTS = 'INFO.PATERNAL_GRANDPARENTS';
  static readonly INFO_MATERNAL_GRANDMOTHER = 'INFO.MATERNAL_GRANDMOTHER';
  static readonly INFO_MATERNAL_GRANDFATHER = 'INFO.MATERNAL_GRANDFATHER';
  static readonly INFO_SAVE = 'INFO.SAVE';
  static readonly INFO_CANCEL = 'INFO.CANCEL';
  static readonly INFO_MEMBER_HEADER = 'INFO.MEMBER_HEADER';
  static readonly INFO_HIDE_LINKS = 'INFO.HIDE_LINKS';
  static readonly INFO_SHOW_LINKS = 'INFO.SHOW_LINKS';
  static readonly INFO_EDIT_MEMBER = 'INFO.EDIT_MEMBER';
  static readonly INFO_ZOOM_IN = 'INFO.ZOOM_IN';
  static readonly INFO_ZOOM_OUT = 'INFO.ZOOM_OUT';
  static readonly INFO_CHANGE_BG = 'INFO.CHANGE_BG';
  static readonly INFO_CHANGE_OPACITY = 'INFO.CHANGE_OPACITY';
  static readonly INFO_CHANGE_PROFILE_IMAGE = 'INFO.CHANGE_PROFILE_IMAGE';
  static readonly INFO_PHOTO_PICKER_HEADER = 'INFO.PHOTO_PICKER_HEADER';
  static readonly INFO_SHOW_CHART = 'INFO.SHOW_CHART';
  static readonly INFO_SHOW_TABLE = 'INFO.SHOW_TABLE';
  static readonly INFO_CHANGE_NODE_SIZE = 'INFO.CHANGE_NODE_SIZE';
  static readonly INFO_CHANGE_TEXT_SIZE = 'INFO.CHANGE_TEXT_SIZE';
  static readonly INFO_CHANGE_HORIZONTAL_SPACING = 'INFO.CHANGE_HORIZONTAL_SPACING';
  static readonly INFO_CHANGE_VERTICAL_SPACING = 'INFO.CHANGE_VERTICAL_SPACING';
  static readonly INFO_FOR_PRINT = 'INFO.FOR_PRINT';
  static readonly INFO_IMAGE_GENERATION = 'INFO.IMAGE_GENERATION';
  static readonly INFO_RELATION_LABEL = 'INFO.RELATION_LABEL';
  static readonly INFO_NAMES = 'INFO.NAMES';
  static readonly INFO_ACTIONS = 'INFO.ACTIONS';
  static readonly INFO_DOB_MODE = 'INFO.DOB_MODE';
  static readonly INFO_DOB_YEAR_ONLY = 'INFO.DOB_YEAR_ONLY';
  static readonly INFO_DOB_NOTE_LABEL = 'INFO.DOB_NOTE_LABEL';
  static readonly INFO_DOD_MODE = 'INFO.DOD_MODE';
  static readonly INFO_DOD_YEAR_ONLY = 'INFO.DOD_YEAR_ONLY';
  static readonly INFO_DOD_NOTE_LABEL = 'INFO.DOD_NOTE_LABEL';
  static readonly INFO_HIDE_BIRTH_DATE = 'INFO.HIDE_BIRTH_DATE';
  static readonly INFO_SHOW_BIRTH_DATE = 'INFO.SHOW_BIRTH_DATE';
  static readonly INFO_TREE_PUT_DESCENDANTS_AT_TOP =
    'INFO.TREE_PUT_DESCENDANTS_AT_TOP';
  static readonly INFO_TREE_PUT_ANCESTORS_AT_TOP =
    'INFO.TREE_PUT_ANCESTORS_AT_TOP';
  static readonly INFO_DELETE_MEMBER = 'INFO.DELETE_MEMBER';
  static readonly INFO_CONFIRM_DELETE_TITLE = 'INFO.CONFIRM_DELETE_TITLE';
  static readonly INFO_CONFIRM_DELETE_MESSAGE = 'INFO.CONFIRM_DELETE_MESSAGE';
  static readonly INFO_DELETE_DEPENDENTS = 'INFO.DELETE_DEPENDENTS';
  static readonly INFO_DELETE = 'INFO.DELETE';
  static readonly INFO_SUCCESS = 'INFO.SUCCESS';
  static readonly INFO_UNSUCCESSFUL = 'INFO.UNSUCCESSFUL';
  static readonly INFO_DELETE_MEMBER_MESSAGE = 'INFO.DELETE_MEMBER_MESSAGE';
  static readonly INFO_BASIC_INFO = 'INFO.BASIC_INFO';
  static readonly INFO_BIRTH_INFO = 'INFO.BIRTH_INFO';
  static readonly INFO_DEATH_INFO = 'INFO.DEATH_INFO';
  static readonly INFO_SAVED = 'INFO.SAVED';
  static readonly INFO_SAVE_FAILED = 'INFO.SAVE_FAILED';
  static readonly INFO_PARTNER_INFO = 'INFO.PARTNER_INFO';
  static readonly INFO_PARTNER_FIRST_NAME = 'INFO.PARTNER_FIRST_NAME';
  static readonly INFO_PARTNER_LAST_NAME = 'INFO.PARTNER_LAST_NAME';
  static readonly INFO_PARTNER_STATUS = 'INFO.PARTNER_STATUS';
  static readonly INFO_UNSAVED_TITLE = 'INFO.UNSAVED_TITLE';
  static readonly INFO_UNSAVED_MESSAGE = 'INFO.UNSAVED_MESSAGE';
  static readonly INFO_STAY = 'INFO.STAY';
  static readonly INFO_LEAVE = 'INFO.LEAVE';
  static readonly INFO_NO_CHANGES = 'INFO.NO_CHANGES';
  static readonly INFO_CLOSE = 'INFO.CLOSE';
  static readonly INFO_RESET = 'INFO.RESET';
  static readonly INFO_UPDATE = 'INFO.UPDATE';
  static readonly INFO_ADD = 'INFO.ADD';
  static readonly INFO_EDIT = 'INFO.EDIT';
  static readonly INFO_EXACT_DATE = 'INFO.EXACT_DATE';
  static readonly INFO_YEAR_ONLY = 'INFO.YEAR_ONLY';
  static readonly INFO_FREE_DATE = 'INFO.FREE_DATE';

  static readonly ADD_PHOTO = 'ADD.PHOTO';

  static readonly GENDER_MALE = 'GENDER.MALE';
  static readonly GENDER_FEMALE = 'GENDER.FEMALE';
  static readonly GENDER_OTHER = 'GENDER.OTHER';

  static readonly RELATION_OWNER = 'RELATION.OWNER';
  static readonly RELATION_MOTHER = 'RELATION.MOTHER';
  static readonly RELATION_FATHER = 'RELATION.FATHER';
  static readonly RELATION_MATERNAL_GRANDMOTHER =
    'RELATION.MATERNAL_GRANDMOTHER';
  static readonly RELATION_MATERNAL_GRANDFATHER =
    'RELATION.MATERNAL_GRANDFATHER';
  static readonly RELATION_PATERNAL_GRANDMOTHER =
    'RELATION.PATERNAL_GRANDMOTHER';
  static readonly RELATION_PATERNAL_GRANDFATHER =
    'RELATION.PATERNAL_GRANDFATHER';

  // Dynamic relations on ANY base
  static readonly RELATION_SON = 'RELATION.SON';
  static readonly RELATION_DAUGHTER = 'RELATION.DAUGHTER';
  static readonly RELATION_BROTHER = 'RELATION.BROTHER';
  static readonly RELATION_SISTER = 'RELATION.SISTER';
  static readonly RELATION_PARTNER = 'RELATION.PARTNER';

  // base + dynamic
  static readonly RELATION_OWNER_SON = 'RELATION.OWNER_SON';
  static readonly RELATION_OWNER_DAUGHTER = 'RELATION.OWNER_DAUGHTER';
  static readonly RELATION_OWNER_BROTHER = 'RELATION.OWNER_BROTHER';
  static readonly RELATION_OWNER_SISTER = 'RELATION.OWNER_SISTER';
  static readonly RELATION_OWNER_PARTNER = 'RELATION.OWNER_PARTNER';

  static readonly RELATION_MOTHER_SON = 'RELATION.MOTHER_SON';
  static readonly RELATION_MOTHER_DAUGHTER = 'RELATION.MOTHER_DAUGHTER';
  static readonly RELATION_MOTHER_BROTHER = 'RELATION.MOTHER_BROTHER';
  static readonly RELATION_MOTHER_SISTER = 'RELATION.MOTHER_SISTER';
  static readonly RELATION_MOTHER_PARTNER = 'RELATION.MOTHER_PARTNER';

  static readonly RELATION_FATHER_SON = 'RELATION.FATHER_SON';
  static readonly RELATION_FATHER_DAUGHTER = 'RELATION.FATHER_DAUGHTER';
  static readonly RELATION_FATHER_BROTHER = 'RELATION.FATHER_BROTHER';
  static readonly RELATION_FATHER_SISTER = 'RELATION.FATHER_SISTER';
  static readonly RELATION_FATHER_PARTNER = 'RELATION.FATHER_PARTNER';

  static readonly RELATION_MATERNAL_GRANDMOTHER_SON =
    'RELATION.MATERNAL_GRANDMOTHER_SON';
  static readonly RELATION_MATERNAL_GRANDMOTHER_DAUGHTER =
    'RELATION.MATERNAL_GRANDMOTHER_DAUGHTER';
  static readonly RELATION_MATERNAL_GRANDMOTHER_BROTHER =
    'RELATION.MATERNAL_GRANDMOTHER_BROTHER';
  static readonly RELATION_MATERNAL_GRANDMOTHER_SISTER =
    'RELATION.MATERNAL_GRANDMOTHER_SISTER';
  static readonly RELATION_MATERNAL_GRANDMOTHER_PARTNER =
    'RELATION.MATERNAL_GRANDMOTHER_PARTNER';

  static readonly RELATION_MATERNAL_GRANDFATHER_SON =
    'RELATION.MATERNAL_GRANDFATHER_SON';
  static readonly RELATION_MATERNAL_GRANDFATHER_DAUGHTER =
    'RELATION.MATERNAL_GRANDFATHER_DAUGHTER';
  static readonly RELATION_MATERNAL_GRANDFATHER_BROTHER =
    'RELATION.MATERNAL_GRANDFATHER_BROTHER';
  static readonly RELATION_MATERNAL_GRANDFATHER_SISTER =
    'RELATION.MATERNAL_GRANDFATHER_SISTER';
  static readonly RELATION_MATERNAL_GRANDFATHER_PARTNER =
    'RELATION.MATERNAL_GRANDFATHER_PARTNER';

  static readonly RELATION_MATERNAL_GRANDMOTHER_FATHER =
    'RELATION.MATERNAL_GRANDMOTHER_FATHER';
  static readonly RELATION_MATERNAL_GRANDMOTHER_MOTHER =
    'RELATION.MATERNAL_GRANDMOTHER_MOTHER';
  static readonly RELATION_MATERNAL_GRANDFATHER_FATHER =
    'RELATION.MATERNAL_GRANDFATHER_FATHER';
  static readonly RELATION_MATERNAL_GRANDFATHER_MOTHER =
    'RELATION.MATERNAL_GRANDFATHER_MOTHER';

  static readonly RELATION_PATERNAL_GRANDMOTHER_SON =
    'RELATION.PATERNAL_GRANDMOTHER_SON';
  static readonly RELATION_PATERNAL_GRANDMOTHER_DAUGHTER =
    'RELATION.PATERNAL_GRANDMOTHER_DAUGHTER';
  static readonly RELATION_PATERNAL_GRANDMOTHER_BROTHER =
    'RELATION.PATERNAL_GRANDMOTHER_BROTHER';
  static readonly RELATION_PATERNAL_GRANDMOTHER_SISTER =
    'RELATION.PATERNAL_GRANDMOTHER_SISTER';
  static readonly RELATION_PATERNAL_GRANDMOTHER_PARTNER =
    'RELATION.PATERNAL_GRANDMOTHER_PARTNER';

  static readonly RELATION_PATERNAL_GRANDFATHER_SON =
    'RELATION.PATERNAL_GRANDFATHER_SON';
  static readonly RELATION_PATERNAL_GRANDFATHER_DAUGHTER =
    'RELATION.PATERNAL_GRANDFATHER_DAUGHTER';
  static readonly RELATION_PATERNAL_GRANDFATHER_BROTHER =
    'RELATION.PATERNAL_GRANDFATHER_BROTHER';
  static readonly RELATION_PATERNAL_GRANDFATHER_SISTER =
    'RELATION.PATERNAL_GRANDFATHER_SISTER';
  static readonly RELATION_PATERNAL_GRANDFATHER_PARTNER =
    'RELATION.PATERNAL_GRANDFATHER_PARTNER';

  static readonly RELATION_PATERNAL_GRANDMOTHER_FATHER =
    'RELATION.PATERNAL_GRANDMOTHER_FATHER';
  static readonly RELATION_PATERNAL_GRANDMOTHER_MOTHER =
    'RELATION.PATERNAL_GRANDMOTHER_MOTHER';
  static readonly RELATION_PATERNAL_GRANDFATHER_FATHER =
    'RELATION.PATERNAL_GRANDFATHER_FATHER';
  static readonly RELATION_PATERNAL_GRANDFATHER_MOTHER =
    'RELATION.PATERNAL_GRANDFATHER_MOTHER';

  // Headers/buttons
  static readonly RELATION_ADD_RELATIVE_HEADER = 'RELATION.ADD_RELATIVE_HEADER';
  static readonly RELATION_CHOOSE_RELATION = 'RELATION.CHOOSE_RELATION';

  // Generic fallbacks
  static readonly RELATION_MATERNAL_GENERIC = 'RELATION.MATERNAL_GENERIC';
  static readonly RELATION_PATERNAL_GENERIC = 'RELATION.PATERNAL_GENERIC';
  static readonly RELATION_UNKNOWN = 'RELATION.UNKNOWN';
  static readonly RELATION_TYPE = 'RELATION.TYPE';

  static readonly TAB_GENERAL_INFO = 'TAB.GENERAL_INFO';
  static readonly TAB_STORIES = 'TAB.STORIES';
  static readonly TAB_BIOGRAPHY = 'TAB.BIOGRAPHY';
  static readonly TAB_MEDIA = 'TAB.MEDIA';
  static readonly TAB_CAREER = 'TAB.CAREER';
  static readonly TAB_ACHIEVEMENTS = 'TAB.ACHIEVEMENTS';
  static readonly TAB_FAVORITES = 'TAB.FAVORITES';
  static readonly TAB_PERSONAL_INFO = 'TAB.PERSONAL_INFO';

  static readonly PARTNER_STATUS_MARRIED = 'PARTNER_STATUS.MARRIED';
  static readonly PARTNER_STATUS_DIVORCED = 'PARTNER_STATUS.DIVORCED';
  static readonly PARTNER_STATUS_SEPARATED = 'PARTNER_STATUS.SEPARATED';
  static readonly PARTNER_STATUS_WIDOWED = 'PARTNER_STATUS.WIDOWED';
  static readonly PARTNER_STATUS_ENGAGED = 'PARTNER_STATUS.ENGAGED';
  static readonly PARTNER_STATUS_PARTNERS = 'PARTNER_STATUS.PARTNERS';
  static readonly PARTNER_STATUS_FRIENDS = 'PARTNER_STATUS.FRIENDS';
  static readonly PARTNER_STATUS_ANNULLED = 'PARTNER_STATUS.ANNULLED';
  static readonly PARTNER_STATUS_UNKNOWN = 'PARTNER_STATUS.UNKNOWN';
  static readonly PARTNER_STATUS_OTHER = 'PARTNER_STATUS.OTHER';

  static readonly BIO_MAIN_BIO = 'BIO.MAIN_BIO';
  static readonly BIO_NOTES = 'BIO.NOTES';
  static readonly BIO_ADD_NOTE = 'BIO.ADD_NOTE';
  static readonly BIO_ADDITIONAL_NOTES = 'BIO.ADDITIONAL_NOTES';
  static readonly BIO_ADDITIONAL_INFO = 'BIO.ADDITIONAL_INFO';
  static readonly BIO_EDIT_NOTE = 'BIO.EDIT_NOTE';
  static readonly BIO_DELETE_NOTE = 'BIO.DELETE_NOTE';
  static readonly BIO_NOTE_TITLE = 'BIO.NOTE_TITLE';
  static readonly BIO_ACTION_NOT_UNDONE = 'BIO.ACTION_NOT_UNDONE';
  static readonly BIO_COMMON_NOTE_TITLE = 'BIO.COMMON_NOTE_TITLE';
  static readonly BIO_NO_NOTES = 'BIO.NO_NOTES';

  static readonly MEDIA_TAB_IMAGES = 'MEDIA.TAB_IMAGES';
  static readonly MEDIA_TAB_VIDEOS = 'MEDIA.TAB_VIDEOS';
  static readonly MEDIA_CHOOSE = 'MEDIA.CHOOSE';
  static readonly MEDIA_UPLOAD = 'MEDIA.UPLOAD';
  static readonly MEDIA_NO_IMAGES = 'MEDIA.NO_IMAGES';
  static readonly MEDIA_NO_VIDEOS = 'MEDIA.NO_VIDEOS';
  static readonly MEDIA_SET_AS_COVER = 'MEDIA.SET_AS_COVER';
  static readonly MEDIA_UPLOADED = 'MEDIA.UPLOADED';
  static readonly MEDIA_UPLOAD_FAILED = 'MEDIA.UPLOAD_FAILED';
  static readonly MEDIA_VIEWER = 'MEDIA.VIEWER';
  static readonly MEDIA_APPLY_FAILED = 'MEDIA.APPLY_FAILED';
  static readonly MEDIA_REMOVE_FROM_GALLERY = 'MEDIA.REMOVE_FROM_GALLERY';
  static readonly MEDIA_PENDING_UPLOADS = 'MEDIA.PENDING_UPLOADS';
  static readonly MEDIA_PENDING_DELETES = 'MEDIA.PENDING_DELETES';
  static readonly MEDIA_APPLIED_ON_SAVE = 'MEDIA.APPLIED_ON_SAVE';
  static readonly MEDIA_EDIT = 'MEDIA.EDIT';
  static readonly MEDIA_DONE = 'MEDIA.DONE';
  static readonly MEDIA_RESET_DELETES = 'MEDIA.RESET_DELETES';

  static readonly CAREER_COMPLETED = 'CAREER.COMPLETED';
  static readonly CAREER_NOT_COMPLETED = 'CAREER.NOT_COMPLETED';
  static readonly CAREER_TAB_EDU = 'CAREER.TAB_EDU';
  static readonly CAREER_TAB_WORK = 'CAREER.TAB_WORK';
  static readonly CAREER_EDU_NAME = 'CAREER.EDU_NAME';
  static readonly CAREER_EDU_QUALIFICATION = 'CAREER.EDU_QUALIFICATION';
  static readonly CAREER_COMPLETION = 'CAREER.COMPLETION';
  static readonly CAREER_START_YEAR = 'CAREER.START_YEAR';
  static readonly CAREER_END_YEAR = 'CAREER.END_YEAR';
  static readonly CAREER_NOTES = 'CAREER.NOTES';
  static readonly CAREER_COL_NAME = 'CAREER.COL_NAME';
  static readonly CAREER_COL_QUALIFICATION = 'CAREER.COL_QUALIFICATION';
  static readonly CAREER_COL_START = 'CAREER.COL_START';
  static readonly CAREER_COL_END = 'CAREER.COL_END';
  static readonly CAREER_COL_COMPLETED = 'CAREER.COL_COMPLETED';
  static readonly CAREER_COL_NOTES = 'CAREER.COL_NOTES';
  static readonly CAREER_COL_ACTIONS = 'CAREER.COL_ACTIONS';
  static readonly CAREER_EMPTY_EDU = 'CAREER.EMPTY_EDU';
  static readonly CAREER_WORK_EMPLOYER = 'CAREER.WORK_EMPLOYER';
  static readonly CAREER_COL_EMPLOYER = 'CAREER.COL_EMPLOYER';
  static readonly CAREER_EMPTY_WORK = 'CAREER.EMPTY_WORK';
  static readonly CAREER_EDU_LIST = 'CAREER.EDU_LIST';
  static readonly CAREER_WORK_LIST = 'CAREER.WORK_LIST';
  static readonly CAREER_WORK_PROFESSION = 'CAREER.WORK_PROFESSION';
  static readonly CAREER_COL_PROFESSION = 'CAREER.COL_PROFESSION';

  static readonly STORIES_TITLE = 'STORIES.TITLE';
  static readonly STORIES_INCLUDED_MEMBERS = 'STORIES.INCLUDED_MEMBERS';
  static readonly STORIES_STORY = 'STORIES.STORY';
  static readonly STORIES_UPDATE = 'STORIES.UPDATE';
  static readonly STORIES_ADD = 'STORIES.ADD';
  static readonly STORIES_STORIES = 'STORIES.STORIES';
  static readonly STORIES_DELETE_STORY = 'STORIES.DELETE_STORY';
  static readonly STORIES_DATE = 'STORIES.DATE';
  static readonly STORIES_CREATED = 'STORIES.CREATED';

  static readonly ACH_ADD = 'ACH.ADD';
  static readonly ACH_UPDATE = 'ACH.UPDATE';
  static readonly ACH_TITLE = 'ACH.TITLE';
  static readonly ACH_CATEGORY_LABEL = 'ACH.CATEGORY_LABEL';
  static readonly ACH_LEVEL_LABEL = 'ACH.LEVEL_LABEL';
  static readonly ACH_ORGANIZATION = 'ACH.ORGANIZATION';
  static readonly ACH_LOCATION = 'ACH.LOCATION';
  static readonly ACH_DATE = 'ACH.DATE';
  static readonly ACH_DATE_MODE = 'ACH.DATE_MODE';
  static readonly ACH_DELETE_TITLE = 'ACH.DELETE_TITLE';
  static readonly ACH_DELETE_MSG = 'ACH.DELETE_MSG';
  static readonly ACH_NO_ACH = 'ACH.NO_ACH';

  static readonly FAV_CATEGORY = 'FAV.CATEGORY_LABEL';
  static readonly FAV_TITLE = 'FAV.TITLE';
  static readonly FAV_NOTES = 'FAV.NOTES';
  static readonly FAV_ADD = 'FAV.ADD';
  static readonly FAV_UPDATE = 'FAV.UPDATE';
  static readonly FAV_LIST = 'FAV.LIST';
  static readonly FAV_EMPTY = 'FAV.EMPTY';
  static readonly FAV_COL_CATEGORY = 'FAV.COL_CATEGORY';
  static readonly FAV_COL_TITLE = 'FAV.COL_TITLE';
  static readonly FAV_COL_NOTES = 'FAV.COL_NOTES';
  static readonly FAV_COL_ACTIONS = 'FAV.COL_ACTIONS';
  static readonly FAV_DELETE_TITLE = 'FAV.DELETE_TITLE';
  static readonly FAV_DELETE_MSG = 'FAV.DELETE_MSG';

  static readonly PERSONAL_IDENTITY = 'PERSONAL.IDENTITY';
  static readonly PERSONAL_CONTACTS = 'PERSONAL.CONTACTS';
  static readonly PERSONAL_RELIGION = 'PERSONAL.RELIGION';
  static readonly PERSONAL_NAME_DAY = 'PERSONAL.NAME_DAY';
  static readonly PERSONAL_HEIGHT = 'PERSONAL.HEIGHT';
  static readonly PERSONAL_WEIGHT = 'PERSONAL.WEIGHT';
  static readonly PERSONAL_BLOOD_TYPE = 'PERSONAL.BLOOD_TYPE';
  static readonly PERSONAL_HANDEDNESS = 'PERSONAL.HANDEDNESS';
  static readonly PERSONAL_SMOKING = 'PERSONAL.SMOKING';
  static readonly PERSONAL_ALLERGIES = 'PERSONAL.ALLERGIES';
  static readonly PERSONAL_CONDITIONS = 'PERSONAL.CONDITIONS';
  static readonly PERSONAL_PHONE = 'PERSONAL.PHONE';
  static readonly PERSONAL_EMAIL = 'PERSONAL.EMAIL';
  static readonly PERSONAL_WEBSITE = 'PERSONAL.WEBSITE';
  static readonly PERSONAL_ADDRESS = 'PERSONAL.ADDRESS';
  static readonly PERSONAL_NOTES = 'PERSONAL.NOTES';

  // Settings / Plans labels
  static readonly SETTINGS_PLANS = 'SETTINGS.PLANS';
  static readonly SETTINGS_PLANS_TITLE = 'SETTINGS.PLANS_TITLE';
  static readonly SETTINGS_PLANS_BEST = 'SETTINGS.PLANS_BEST';
  static readonly SETTINGS_PLANS_PRICE_PER_DAY = 'SETTINGS.PLANS_PRICE_PER_DAY';
  static readonly SETTINGS_PLANS_TOTAL = 'SETTINGS.PLANS_TOTAL';
  static readonly SETTINGS_PLANS_NOTES = 'SETTINGS.PLANS_NOTES';
  static readonly SETTINGS_PLANS_PERKS_TITLE = 'SETTINGS.PLANS_PERKS_TITLE';
  static readonly SETTINGS_PLANS_PERK_FEATURES = 'SETTINGS.PLANS_PERK_FEATURES';
  static readonly SETTINGS_PLANS_PERK_BACKUP = 'SETTINGS.PLANS_PERK_BACKUP';
  static readonly SETTINGS_PLANS_PERK_SUPPORT = 'SETTINGS.PLANS_PERK_SUPPORT';
  static readonly SETTINGS_PLANS_CHOOSE = 'SETTINGS.PLANS_CHOOSE';

  // Plan names
  static readonly SETTINGS_PLAN_6M = 'SETTINGS.PLAN_6M';
  static readonly SETTINGS_PLAN_1Y = 'SETTINGS.PLAN_1Y';
  static readonly SETTINGS_PLAN_2Y = 'SETTINGS.PLAN_2Y';
  static readonly SETTINGS_PLAN_FREE = 'SETTINGS.PLAN_FREE';
  static readonly SETTINGS_PLAN_FREE_DESC = 'SETTINGS.PLAN_FREE_DESC';
  static readonly SETTINGS_PLAN_FREE_DURATION = 'SETTINGS.PLAN_FREE_DURATION';
  static readonly SETTINGS_PLAN_FREE_FEATURE_MEMBERS =
    'SETTINGS.PLAN_FREE.FEATURE_MEMBERS';
  static readonly SETTINGS_PLAN_FREE_FEATURE_SECTIONS =
    'SETTINGS.PLAN_FREE.FEATURE_SECTIONS';
  static readonly SETTINGS_PLAN_FREE_FEATURE_NO_MEDIA =
    'SETTINGS.PLAN_FREE.FEATURE_NO_MEDIA';
  static readonly SETTINGS_PLAN_FREE_FEATURE_SECURITY =
    'SETTINGS.PLAN_FREE.FEATURE_SECURITY';
  static readonly SETTINGS_PLAN_6M_DESC = 'SETTINGS.PLAN_6M_DESC';
  static readonly SETTINGS_PLAN_1Y_DESC = 'SETTINGS.PLAN_1Y_DESC';
  static readonly SETTINGS_PLAN_2Y_DESC = 'SETTINGS.PLAN_2Y_DESC';
  static readonly SETTINGS_PLAN_PAID_FEATURE_MEMBERS =
    'SETTINGS.PLAN_PAID.FEATURE_MEMBERS';
  static readonly SETTINGS_PLAN_PAID_FEATURE_MEDIA =
    'SETTINGS.PLAN_PAID.FEATURE_MEDIA';
  static readonly SETTINGS_PLAN_PAID_FEATURE_SHARING =
    'SETTINGS.PLAN_PAID.FEATURE_SHARING';
  static readonly SETTINGS_PLAN_PAID_FEATURE_SUPPORT =
    'SETTINGS.PLAN_PAID.FEATURE_SUPPORT';
  static readonly SETTINGS_PLANS_INCLUDED = 'SETTINGS.PLANS_INCLUDED';

  static readonly ADMIN_EYEBROW = 'ADMIN.EYEBROW';
  static readonly ADMIN_TITLE = 'ADMIN.TITLE';
  static readonly ADMIN_SUBTITLE = 'ADMIN.SUBTITLE';
  static readonly ADMIN_STATS_USERS = 'ADMIN.STATS_USERS';
  static readonly ADMIN_STATS_MEMBERS = 'ADMIN.STATS_MEMBERS';
  static readonly ADMIN_STATS_SELECTED = 'ADMIN.STATS_SELECTED';
  static readonly ADMIN_STATS_SELECTED_NONE = 'ADMIN.STATS_SELECTED_NONE';
  static readonly ADMIN_STATS_DATA_RECORDS = 'ADMIN.STATS_DATA_RECORDS';
  static readonly ADMIN_STATS_SELECTED_DATA = 'ADMIN.STATS_SELECTED_DATA';
  static readonly ADMIN_USERS_SECTION = 'ADMIN.USERS_SECTION';
  static readonly ADMIN_USERS_SUBTITLE = 'ADMIN.USERS_SUBTITLE';
  static readonly ADMIN_REFRESH = 'ADMIN.REFRESH';
  static readonly ADMIN_TABLE_USER = 'ADMIN.TABLE_USER';
  static readonly ADMIN_TABLE_LANGUAGE = 'ADMIN.TABLE_LANGUAGE';
  static readonly ADMIN_TABLE_MEMBERS = 'ADMIN.TABLE_MEMBERS';
  static readonly ADMIN_TABLE_PROFILES = 'ADMIN.TABLE_PROFILES';
  static readonly ADMIN_TABLE_DATA_USAGE = 'ADMIN.TABLE_DATA_USAGE';
  static readonly ADMIN_TABLE_LAST_CHANGE = 'ADMIN.TABLE_LAST_CHANGE';
  static readonly ADMIN_TABLE_PLAN = 'ADMIN.TABLE_PLAN';
  static readonly ADMIN_SUBSCRIPTION_ASSIGN = 'ADMIN.SUBSCRIPTION_ASSIGN';
  static readonly ADMIN_SUBSCRIPTION_APPLY = 'ADMIN.SUBSCRIPTION_APPLY';
  static readonly ADMIN_SUBSCRIPTION_UPDATED = 'ADMIN.SUBSCRIPTION_UPDATED';
  static readonly ADMIN_SUBSCRIPTION_UPDATE_ERROR =
    'ADMIN.SUBSCRIPTION_UPDATE_ERROR';
  static readonly ADMIN_SUBSCRIPTION_SOURCE_PAID =
    'ADMIN.SUBSCRIPTION_SOURCE_PAID';
  static readonly ADMIN_SUBSCRIPTION_SOURCE_ADMIN =
    'ADMIN.SUBSCRIPTION_SOURCE_ADMIN';
  static readonly ADMIN_SUBSCRIPTION_SOURCE_UNKNOWN =
    'ADMIN.SUBSCRIPTION_SOURCE_UNKNOWN';
  static readonly ADMIN_FILTER_PLACEHOLDER = 'ADMIN.FILTER_PLACEHOLDER';
  static readonly ADMIN_FILTER_NUMBER_PLACEHOLDER =
    'ADMIN.FILTER_NUMBER_PLACEHOLDER';
  static readonly ADMIN_PAGINATION_PAGE = 'ADMIN.PAGINATION_PAGE';
  static readonly ADMIN_PAGINATION_ROWS_PER_PAGE =
    'ADMIN.PAGINATION_ROWS_PER_PAGE';
  static readonly ADMIN_PAGINATION_PREV = 'ADMIN.PAGINATION_PREV';
  static readonly ADMIN_PAGINATION_NEXT = 'ADMIN.PAGINATION_NEXT';
  static readonly ADMIN_LOADING = 'ADMIN.LOADING';
  static readonly ADMIN_USERS_EMPTY = 'ADMIN.USERS_EMPTY';
  static readonly ADMIN_UNKNOWN_USER = 'ADMIN.UNKNOWN_USER';
  static readonly ADMIN_LAST_CHANGE_NEVER = 'ADMIN.LAST_CHANGE_NEVER';
  static readonly ADMIN_PLAN_EXPIRES = 'ADMIN.PLAN_EXPIRES';
  static readonly ADMIN_VIEW_MEMBERS = 'ADMIN.VIEW_MEMBERS';
  static readonly ADMIN_MEMBERS_SECTION = 'ADMIN.MEMBERS_SECTION';
  static readonly ADMIN_MEMBERS_SUBTITLE = 'ADMIN.MEMBERS_SUBTITLE';
  static readonly ADMIN_MEMBERS_IDLE = 'ADMIN.MEMBERS_IDLE';
  static readonly ADMIN_SELECT_USER_PROMPT = 'ADMIN.SELECT_USER_PROMPT';
  static readonly ADMIN_MEMBERS_EMPTY = 'ADMIN.MEMBERS_EMPTY';
  static readonly ADMIN_MEMBERS_ACCESS_DENIED =
    'ADMIN.MEMBERS_ACCESS_DENIED';
  static readonly ADMIN_MEMBER_NAME = 'ADMIN.MEMBER_NAME';
  static readonly ADMIN_MEMBER_ROLE = 'ADMIN.MEMBER_ROLE';
  static readonly ADMIN_MEMBER_RELATION = 'ADMIN.MEMBER_RELATION';
  static readonly ADMIN_MEMBER_STATUS = 'ADMIN.MEMBER_STATUS';
  static readonly ADMIN_MEMBER_LAST_CHANGE = 'ADMIN.MEMBER_LAST_CHANGE';
  static readonly ADMIN_MEMBER_DATA_USAGE = 'ADMIN.MEMBER_DATA_USAGE';
  static readonly ADMIN_MEMBER_ALIVE = 'ADMIN.MEMBER_ALIVE';
  static readonly ADMIN_MEMBER_DECEASED = 'ADMIN.MEMBER_DECEASED';
  static readonly ADMIN_MEMBER_PROFILE_PRESENT =
    'ADMIN.MEMBER_PROFILE_PRESENT';
  static readonly ADMIN_MEMBER_PROFILE_MISSING =
    'ADMIN.MEMBER_PROFILE_MISSING';
  static readonly ADMIN_LOAD_USERS_ERROR = 'ADMIN.LOAD_USERS_ERROR';
  static readonly ADMIN_LOAD_MEMBERS_ERROR = 'ADMIN.LOAD_MEMBERS_ERROR';
  static readonly ADMIN_NAV_LABEL = 'ADMIN.NAV_LABEL';

  // CONTACT
  static readonly CONTACT_TITLE = 'CONTACT.TITLE';
  static readonly CONTACT_SUBTITLE = 'CONTACT.SUBTITLE';
  static readonly CONTACT_CARD_EMAIL = 'CONTACT.CARD.EMAIL';
  static readonly CONTACT_CARD_ADDRESS = 'CONTACT.CARD.ADDRESS';
  static readonly CONTACT_CARD_HOURS = 'CONTACT.CARD.HOURS';
  static readonly CONTACT_CARD_HOURS_VALUE = 'CONTACT.CARD.HOURS_VALUE';

  static readonly CONTACT_FULL_NAME = 'CONTACT.FORM.FULL_NAME';
  static readonly CONTACT_FULL_NAME_ERR = 'CONTACT.FORM.FULL_NAME_ERR';
  static readonly CONTACT_EMAIL = 'CONTACT.FORM.EMAIL';
  static readonly CONTACT_EMAIL_ERR = 'CONTACT.FORM.EMAIL_ERR';
  static readonly CONTACT_TOPIC = 'CONTACT.FORM.TOPIC';
  static readonly CONTACT_TOPIC_ERR = 'CONTACT.FORM.TOPIC_ERR';
  static readonly CONTACT_MESSAGE = 'CONTACT.FORM.MESSAGE';
  static readonly CONTACT_MESSAGE_ERR = 'CONTACT.FORM.MESSAGE_ERR';
  static readonly CONTACT_CONSENT_PREFIX = 'CONTACT.FORM.CONSENT_PREFIX';
  static readonly CONTACT_CONSENT_SUFFIX = 'CONTACT.FORM.CONSENT_SUFFIX';
  static readonly HOME_SOUND_MUTE = 'HOME.SOUND.MUTE';
  static readonly HOME_SOUND_PLAY = 'HOME.SOUND.PLAY';
  static readonly HOME_CONTROL_COLLAPSE_CHART_TOOLS = 'HOME.CONTROL.COLLAPSE_CHART_TOOLS';
  static readonly HOME_CONTROL_EXPAND_CHART_TOOLS = 'HOME.CONTROL.EXPAND_CHART_TOOLS';
  static readonly HOME_CONTROL_SECTION_LAYOUT = 'HOME.CONTROL.SECTION_LAYOUT';
  static readonly HOME_CONTROL_LABEL_NODE_SIZE = 'HOME.CONTROL.LABEL_NODE_SIZE';
  static readonly HOME_CONTROL_LABEL_TEXT_SIZE = 'HOME.CONTROL.LABEL_TEXT_SIZE';
  static readonly HOME_CONTROL_LABEL_BG_OPACITY = 'HOME.CONTROL.LABEL_BG_OPACITY';
  static readonly HOME_CONTROL_LABEL_H_SPACING = 'HOME.CONTROL.LABEL_H_SPACING';
  static readonly HOME_CONTROL_LABEL_V_SPACING = 'HOME.CONTROL.LABEL_V_SPACING';
  static readonly HOME_EXPORT_BACKGROUND = 'HOME.EXPORT.BACKGROUND';
  static readonly HOME_EXPORT_REFRESH = 'HOME.EXPORT.REFRESH_PREVIEW';
  static readonly HOME_EXPORT_PREPARING = 'HOME.EXPORT.PREPARING';
  static readonly CONTACT_SEND = 'CONTACT.FORM.SEND';
  static readonly CONTACT_CHAR_REMAINING = 'CONTACT.CHAR_REMAINING';

  static readonly CONTACT_SENT_TITLE = 'CONTACT.STATUS.SENT_TITLE';
  static readonly CONTACT_SENT_DESC = 'CONTACT.STATUS.SENT_DESC';
  static readonly CONTACT_ERROR_DESC = 'CONTACT.STATUS.ERROR_DESC';

  static readonly CONTACT_TOPIC_SUPPORT = 'CONTACT.TOPICS.SUPPORT';
  static readonly CONTACT_TOPIC_BILLING = 'CONTACT.TOPICS.BILLING';
  static readonly CONTACT_TOPIC_SUGGESTION = 'CONTACT.TOPICS.SUGGESTION';
  static readonly CONTACT_TOPIC_OTHER = 'CONTACT.TOPICS.OTHER';
}
