export enum FavoriteCategory {
  BOOK = 'BOOK',
  MOVIE = 'MOVIE',
  SONG = 'SONG',
  MUSIC = 'MUSIC',
  QUOTE = 'QUOTE',
  AUTHOR = 'AUTHOR',
  ACTOR = 'ACTOR',
  SPORT = 'SPORT',
  TEAM = 'TEAM',
  RESTAURANT = 'RESTAURANT',
  DISH = 'DISH',
  DRINK = 'DRINK',
  GAME = 'GAME',
  HOBBY = 'HOBBY',
  PLACE = 'PLACE',
  CITY = 'CITY',
  COUNTRY = 'COUNTRY',
  COLOR = 'COLOR',
  ANIMAL = 'ANIMAL',
  OTHER = 'OTHER',
}
