export enum PartnerStatus {
  MARRIED = 'MARRIED',
  DIVORCED = 'DIVORCED',
  SEPARATED = 'SEPARATED',
  WIDOWED = 'WIDOWED',
  ENGAGED = 'ENGAGED',
  PARTNERS = 'PARTNERS',
  FRIENDS = 'FRIENDS',
  ANNULLED = 'ANNULLED',
  UNKNOWN = 'UNKNOWN',
  OTHER = 'OTHER',
}